export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_ALL_POST_SUCCESS = 'DELETE_ALL_POST_SUCCESS';
export const SELECTED_POST = 'SELECTED_POST';
export const PAGER_CHANGE = 'PAGER_CHANGE';
export const RAISE_ERROR = 'RAISE_ERROR';
