export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const DISMISS_POST = 'DISMISS_POST';
export const DISMISS_ALL_POST = 'DISMISS_ALL_POST';
export const SELECT_POST = 'SELECT_POST';
export const PAGER_CHANGE = 'PAGER_CHANGE';
export const RAISE_ERROR = 'RAISE_ERROR';
